/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package test;

import org.hibernate.Session;
import org.hibernate.SessionFactory;
import org.hibernate.Transaction;
import org.hibernate.cfg.Configuration;

public class App {
    public static void main(String[] args) {
       spy s=new spy();
       s.setSid(2);
       s.setSname("David");
       s.setColor("Red");
       
       
       Configuration con =new Configuration().configure().addAnnotatedClass(spy.class);
       SessionFactory sf=con.buildSessionFactory();
       Session session =sf.openSession();
       Transaction tx=session.beginTransaction();
       session.save(s);
       tx.commit();
       
    }
}
